server:
  port: 8088

spring:
  application:
    name: wt-images
  datasource:
    password: Crescent1!
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wt-micro-project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false

simple4h:
  storage:
    qiniu:
      endpoint: https://wtimages.cxm520hyq.com
      accessKey: 08boC1zdPtkc6PBIGeZ-_UAzan4QE_Fr112nFk4_
      secretKey: 5gc0PrtwbrmbwreLmu2y0J37RQoHlZAT6BS13MG_
      bucketName: wt-images

mybatis:
  mapper-locations: classpath:mappers/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

