package com.simple4h.dao;

import com.simple4h.domain.WtCategory;
import com.simple4h.domain.WtCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WtCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    long countByExample(WtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    int deleteByExample(WtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    int insert(WtCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    int insertSelective(WtCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    WtCategory selectOneByExample(WtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    WtCategory selectOneByExampleSelective(@Param("example") WtCategoryExample example, @Param("selective") WtCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    List<WtCategory> selectByExampleSelective(@Param("example") WtCategoryExample example, @Param("selective") WtCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    List<WtCategory> selectByExample(WtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    WtCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WtCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    WtCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    WtCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WtCategory record, @Param("example") WtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WtCategory record, @Param("example") WtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WtCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WtCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") WtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}