package com.simple4h.dao;

import com.simple4h.domain.WtStorage;
import com.simple4h.domain.WtStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WtStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    long countByExample(WtStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    int deleteByExample(WtStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    int insert(WtStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    int insertSelective(WtStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    WtStorage selectOneByExample(WtStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    WtStorage selectOneByExampleSelective(@Param("example") WtStorageExample example, @Param("selective") WtStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    List<WtStorage> selectByExampleSelective(@Param("example") WtStorageExample example, @Param("selective") WtStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    List<WtStorage> selectByExample(WtStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    WtStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WtStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    WtStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    WtStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WtStorage record, @Param("example") WtStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WtStorage record, @Param("example") WtStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WtStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WtStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") WtStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}